"""Small image value object used for study thumbnails.

Thumbnails are generated by Infrastructure from DICOM pixel data but consumed
by Presentation, so the produced artifact is defined here as plain data.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Thumbnail:
    """An 8-bit grayscale image, tightly packed row-major."""

    width: int
    height: int
    data: bytes

    @property
    def pixel_count(self) -> int:
        """Return the number of pixels in the thumbnail."""
        return self.width * self.height

    def validate(self) -> bool:
        """Return whether the payload matches the declared dimensions."""
        return len(self.data) == self.pixel_count
